# Generated by Django 2.0.2 on 2018-03-01 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.IntegerField(default=None)),
                ('course_department', models.CharField(default=None, max_length=100)),
                ('course_name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsStudyGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course', to='studygroup.Courses')),
            ],
        ),
        migrations.AddField(
            model_name='studentsstudygroups',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='studygroup.StudyGroup'),
        ),
        migrations.AddField(
            model_name='studentsstudygroups',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
