# Generated by Django 2.0.3 on 2018-04-05 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0003_message'),
        ('studygroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='chat_room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room', to='groupchat.Room'),
        ),
    ]
