# Generated by Django 2.0.3 on 2018-04-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0002_auto_20180327_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True, db_index=True)),
                ('room', models.ForeignKey(on_delete=None, to='groupchat.Room')),
            ],
        ),
    ]
