# Generated by Django 2.0.2 on 2018-03-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.IntegerField(default=None),
        ),
    ]
