# Generated by Django 2.0.2 on 2018-03-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180301_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='group',
            new_name='user_type',
        ),
    ]
