# Generated by Django 2.0.2 on 2018-03-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180301_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reports',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
