# Generated by Django 2.0.2 on 2018-03-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180301_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reports',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
