# Generated by Django 2.0.2 on 2018-03-22 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroup', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='filepath',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='groupd_id',
        ),
        migrations.AddField(
            model_name='notes',
            name='studygroup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='studygroup_note', to='studygroup.StudyGroup'),
        ),
        migrations.AddField(
            model_name='notes',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
