# Generated by Django 2.0.2 on 2018-03-09 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroup', '0001_initial'),
        ('calendars', '0003_auto_20180305_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='event',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='day',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='month',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='year',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date_time',
            field=models.DateTimeField(default=None, verbose_name='Meeting Time'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='studygroup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='studygroup_meeting', to='studygroup.StudyGroup'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
