# Generated by Django 2.0.2 on 2018-03-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_auto_20180309_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
